export type UserPlan = 'Discovery' | 'Zoya Pro' | 'Zoya Premium';

export interface AIAnalysisResult {
  metric_analysis: {
    risk: { comment: string; recommendation: string };
    discipline: { comment: string; recommendation: string };
    consistency: { comment: string; recommendation: string };
  };
  summary: {
    total_pnl: number;
    winrate: number;
    avg_win: number;
    avg_loss: number;
    largest_win: number;
    largest_loss: number;
  };
  scores: {
    risk_score: number;
    discipline_score: number;
    consistency_score: number;
  };
  alerts: {
    type: 'risk' | 'discipline' | 'consistency' | 'strategy';
    severity: 'low' | 'medium' | 'high';
    message: string;
  }[];
  actions: {
    priority: number;
    action: string;
    reason: string;
  }[];
  coach_decision: {
    status: 'green' | 'orange' | 'red';
    action: 'continue' | 'reduce_risk' | 'stop_trading';
  };
  global_recommendation: string;
  premiumReport?: string; // Narrative report generated by DeepSeek V4 for Premium users
}

export interface AIUsageLog {
  userId: string;
  model: string;
  tokens: number;
  cost: number;
  plan: UserPlan;
  timestamp: any; // Firestore Timestamp
}
